spring:
  cloud:
    discovery:
      enabled: false
    kubernetes:
      enabled: false
    gateway:
      routes:
        - id: service-order
          uri: http://service-order
          predicates:
            - Path=/cart/**
        - id: service-order
          uri: http://service-order
          predicates:
            - Path=/order/**
        - id: service-game
          uri: http://service-game
          predicates:
            - Path=/game/**