apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-order
  namespace: store
  labels:
    app: service-order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-order
  template:
    metadata:
      labels:
        app: service-order
    spec:
      containers:
        - name: service-order
          image: store-service-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /actuator/health/readiness
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 80
              path: /actuator/health/liveness
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: service-order
  labels:
    app: service-order
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: service-order
  type: ClusterIP